checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'spec/*'
coding_style:
    php: {  }
build:
    environment:
        php:
            version: 5.6.18
    tests:
      override:
          - bin/phpspec run
          - bin/phpunit
