checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'spec/*'
coding_style:
    php: {  }
build:
    environment:
        php:
            version: 5.6.18
    tests:
      override:
          - bin/phpunit -v
    project_setup:
        before:
          - mysql -e "CREATE DATABASE symfony"
        # after:
          # - bin/console doctrine:fixtures:load --no-interaction