# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: userpass
                        roles: 'ROLE_USER'
                    admin:
                        password: adminpass
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: secured
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - app.token_authenticator
            switch_user: { role: ROLE_SUPER_ADMIN, parameter:_take_user }


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
